### PR TITLE
Add PHP 7/8 compatibility by updating constructor to use __construct

### LINKED ISSUE #1: an issue with PHP 8.x and this plugin
Having a problem getting this plugin's settings screen to show up in Wordpress 

I I try to manually go to:  https://mywpsitedns/wp-admin/options-general.php?page=http-authentication%2Fhttp-authentication.php 
but I get the error:

"Sorry, you are not allowed to access this page."

When I mouse over "settings" on the left side of the wp-admin area, I dont see the "HTTP Auth" settings there.  I do see it on another site though that I have.

It turns out that if I downgrade my ubuntu 22.04 distro's PHP to 7.4 then it works again.

There seems to be an issue with PHP 8.x and this plugin.

### PR DESCRIPTION
**Pull request by mvl22**
Fixes https://github.com/dwc/wordpress-plugin-http-authentication/issues/1

I release this contribution into the public domain, so there is no copyright restriction. No attribution should be added, please.

### CODE REVIEW

**Comment by dwc** [comment]
Thanks for the PR! I'll release a new version shortly.

**Comment by mvl22** [comment]
> Thanks for the PR! I'll release a new version shortly.

Thanks. I think that the number 4.5 has to be changed in the comment header of the main file - sorry, I had forgotten that Wordpress uses that as actual metadata. The version number hasn't updated on the [release page](https://wordpress.org/plugins/http-authentication/).

**Comment by dwc** [comment]
No worries, it's updated now!

https://wordpress.org/plugins/http-authentication/

**Comment by MattWeatherford** [comment]
Thank you for fixing this - much appreciated !

**Pull request merged**
